### PR TITLE
Fix tuples/arrays not being handled correctly

### PR DESCRIPTION
**Pull request by davesque**
### What was wrong?

As mentioned in #37 and #39 , there are issues with signatures involving tuple and array types.  This PR fixes those issues by using more up-to-date parsing of ABI types.

### How was it fixed?

* Refactored the `normalize_function_signature` utility function to use the `eth-abi` package's type parsing and normalizing features
* Updated some regexes so that solidity code parsing functions correctly detect `ufixed` and `fixed` types
* Removed obsoleted code

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by ligi** [comment]
@pipermerriam can you please merge this or is there a blocker?

context: https://github.com/ethereum-lists/4bytes/issues/37

**Comment by pipermerriam** [comment]
@ligi I'll get it merged and deployed Monday.  I don't want to accidentally break it just before the weekend.

**Comment by ligi** [comment]
push

**Comment by pipermerriam** [comment]
Merged and confirmed this is working (but not yet deployed to the production environment).

Should have the production env updated either later today or early tomorrow.  You can see the staging environment here if anyone wants to try out any other examples: http://app.4byte.directory/signatures/

**Pull request merged**
